baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Portfolio"
theme = "aafu"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
    title = "Мокрушин Александр. Технический писатель"
    author = "Мокрушин Александр"
    description = "Резюме"
    # copyright = ""

    [params.theme]
        # Available themes are 'light', 'dark', 'pinkish' and 'green'
        mainTheme = "green"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = false
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Мокрушин Александр"
		tagline = "Технический писатель"
		location = "Ижевск, Российская Федерация"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-telegram"
            url = "https://t.me/Mokrushin_AI"
            title = "Telegram"
        [[params.social.list]]
            class = "fas"
            icon = "fa-envelope-square"
            url = "mailto:alexandrmokrushin@gmail.com"
            title = "email"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/fish-train"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/%D0%B0%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80-%D0%BC%D0%BE%D0%BA%D1%80%D1%83%D1%88%D0%B8%D0%BD-a8472b1a9/"
            title = "LinkedIn"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "portfolio"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "Обо мне"
        icon = "fas fa-user"
        description = """
Меня зовут Александр, я технический писатель.

Разрабатываю документацию на программное обеспечение 9 лет. Помогаю софтверным компаниям создавать удобную и понятную документацию для пользователей, администраторов и разработчиков.

Я не только работаю с текстом, но и:

- внедряю технологии и выстраиваю процессы документирования,
- обучаю сотрудников,
- управляю командой,
- пишу тексты для интерфейсов,
- автоматизирую разработку документации,
- помогаю писать инженерам о технологиях и продуктах компании,
- развиваю базу знаний.

Мне интересны проекты, в которых используется или внедряется принцип docs as code.
   """
    # Experience section
    [params.experience]
        title = "Опыт работы"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = ""
            dates = "Май 2019 – настоящее время"
            link = "https://www.performance-lab.ru/"
            company = "Performance Lab"
            details = """
- Ведение базы знаний и разработка документации на проекте «Нагрузочное тестирование систем ВТБ»
- Разработка документации и ПМИ на функциональные блоки АПК «Безопасный город», адаптеры «КАМИ» и «Кобра»
- Технологическая поддержка документирования
   """
        [[params.experience.list]]
            position = ""
            dates = "Январь 2018 – май 2019"
            link = "https://technoserv.com/"
            company = "Техносерв Менеджмент"
            details = """
- Разработка документации, ТЗ, ПМИ на программные комплексы ЕГИССО и «Клиентская служба ПФР»
- Управление командой
- Работа с новыми сотрудниками и кандидатами
- Администрирование Confluence
- Технологическая поддержка документирования
   """
        [[params.experience.list]]
            position = ""
            dates = "Июль 2017 – декабрь 2017"
            link = "#"
            company = "Онлайн-Решения"
            details = """
- Разработка документации, ТЗ, ПМИ на программный комплекс «Клиентская служба ПФР»
- Администрирование Confluence
- Технологическая поддержка документирования
   """
        [[params.experience.list]]
            position = ""
            dates = "Октябрь 2011 – июль 2017"
            link = "https://www.directum.ru/"
            company = "Directum"
            details = """
- Разработка документации для систем: DIRECTUM, Prestima, КАС «Бизнес Люкс», Synerdocs
- Управление командой
- Разработка функциональности веб-справки
- Создание обучающих видеороликов
- Работа с новыми сотрудниками и кандидатами
- UX-аналитика
- Технологическая поддержка документирования
   """

    # Education section
    [params.education]
        title = "Образование"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            college = "Ижевский государственный технический университет им. М.Т. Калашникова"
            dates = "2005 – 2010"
            #degree = "Специалист по защите информации"
            degree = "Специалист по защите информации"
            code = "090105"
            spec = "Комплексное обеспечение информационной безопасности автоматизированных систем"
            # thesis_title = "Комплексное обеспечение информационной безопасности автоматизированных систем"
            # thesis_link = "#"

    # Publication section
    [params.publication]
        title = "Публикации"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["title", "date", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Повышаем масштабируемость с DIRECTUM 5.4"
            authors = ""
            date = "10 апреля 2017"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/72375"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Развиваем подписание и шифрование в DIRECTUM 5.4"
            authors = ""
            date = "3 апреля 2017"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/72268"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Управляем выполнением кода на серверах"
            authors = ""
            date = "27 марта 2017"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/72134"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Управляем входящими и исходящими в DIRECTUM 5.3"
            authors = ""
            date = "5 сентября 2016"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/1101"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Веб-доступ, видео, мобильные решения и другие новинки документации"
            authors = ""
            date = "27 января 2016"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/1013"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Сдаем объекты в архив системы"
            authors = ""
            date = "14 января 2016"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/1004"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Создать диалог легко и просто"
            authors = ""
            date = "16 декабря 2015"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/987"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Как добавить свои видеоролики в справку"
            authors = ""
            date = "7 августа 2015"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/958"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Оптимизация и повышение стабильности DIRECTUM 5.1"
            authors = ""
            date = "13 февраля 2015"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/904"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Новинки DIRECTUM 5.1 для разработчиков"
            authors = ""
            date = "30 января 2015"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/892"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Обновленный ISBL-редактор в DIRECTUM 5.1"
            authors = ""
            date = "28 января 2015"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/891"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Справка на новом уровне"
            authors = ""
            date = "26 января 2015"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/889"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Оптимизация репликации в DIRECTUM 5.0"
            authors = ""
            date = "11 марта 2014"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/764"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Агент веб-доступа DIRECTUM 5.0"
            authors = ""
            date = "18 февраля 2014"
            journal = "· Directum Club"
            link = "https://club.directum.ru/post/748"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Электронная подпись с помощью Microsoft Outlook 2010"
            authors = ""
            date = "4 июня 2013"
            journal = "· ECM-Journal"
            link = "https://ecm-journal.ru/post/Ehlektronnaja-podpis-s-pomoshhju-Microsoft-Outlook-2010.aspx"
            type = "Journal Articles"

    # Project section
    [params.project]
        title = "Проекты"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Нагрузочное тестирование систем ВТБ"
            #url = "#"
            description = """
- Ведение базы знаний
- Документирование средств НТ
- Редактура статей инженеров о технологиях и продуктах компании
- Обучение сотрудников
   """
        [[params.project.list]]
            title = "АПК «Безопасный город»"
            url = "http://www.apkbg.ru/"
            description = """
- Документирование функциональных модулей АПК БГ, адаптеров «КАМИ» и «Кобра»
- Разработка ПМИ
   """
        [[params.project.list]]
            title = "ЕГИССО"
            url = "http://egisso.ru/site/"
            description = """
- Документирование ПК ЕГИССО
- Разработка ТЗ и ПМИ
- Управление командой
- Разработка и внедрение стайлгайда
- Работа с новыми сотрудниками и кандидатами
- Администрирование Confluence
   """
        [[params.project.list]]
            title = "Клиентская служба ПФР"
            #url = "#"
            description = """
- Документирование ПК «Клиентская служба ПФР»
- Разработка ТЗ и ПМИ
- Администрирование Confluence
   """
        [[params.project.list]]
            title = "Directum "
            url = "https://www.directum.ru/"
            description =  """
- Документирование ECM Directum 4.8-5.5
- Разработка функциональности веб-справки и видеоплеера
- Управление командой
- Работа с новыми сотрудниками и кандидатами
- Создание обучающих видеороликов
- UX-аналитика и разработка текстов интерфейсов
- Технологическая поддержка документирования
   """
        # [[params.project.list]]
        #     title = "Synerdocs"
        #     url = "https://www.synerdocs.ru/"
        #     description = "Разработка документации"
        # [[params.project.list]]
        #     title = "Prestima"
        #     url = "https://prestima.ru/"
        #     description = "Разработка документации"
        # [[params.project.list]]
        #     title = "КАС «Бизнес-Люкс»"
        #     url = "https://npo-comp.ru/cms"
        #     description = "Разработка документации"

    # Skill section
    # [params.skill]
    #     title = "Skills"
    #     panelId = "skill-panel"
    #     icon = "fas fa-cogs"

    #     [[params.skill.list]]
    #         skill = "Skill 1, Skill 2"
    #         skillrating = 90
    #     [[params.skill.list]]
    #         skill = "Skill 3"
    #         skillrating = 80
    #     [[params.skill.list]]
    #         skill = "Skill 4"
    #         skillrating = 50

    # Portfolio section
    [params.portfolio]
        title = "Примеры работ"
        icon = "fas fa-file-code"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["title"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Учебные проекты", "Документация", "Разработка"]

        [[params.portfolio.list]]
            title = "Docs as Code"
            type = "Учебные проекты"
            link = "https://fish-train.github.io/flnt-test"
            description = """
Цель: познакомиться с принципом Docs as Code, изучить технологии и инструменты:

- Foliant – инструмент создания документации,
- Markdown – язык разметки,
- Git – система контроля  версий,
- GitHub Pages – хостинг,
- Travis CI – веб-сервис для сборки и тестирования ПО,
- VS Code – текстовый редактор.

Дополнительно рассмотрел работу с Docker, Swagger и GostDOWN.
   """

        [[params.portfolio.list]]
            title = "Sphinx и reStructuredText"
            type = "Учебные проекты"
            link = "https://sph-learning.readthedocs.io/ru/latest/index.html"
            description = """
Цель: познакомиться с Sphinx и reStructuredText.

Задачи:

- Создать проект Sphinx для документации на языке разметки reStructuredText.
- Генерировать документацию в формате HTML.
- Генерировать документацию в формате PDF.
- Хранить исходники в Git.
- Публиковать сайт с документацией на ReadTheDocs
   """
            
            [[params.portfolio.list]]
            title = "HelpDesk. Работа с заявками"
            type = "Документация"
            link = "https://docs.google.com/document/d/12rFx6z8B30qPU-hLLtOoPsvXAd37ZKr87d-kpAPOghw/edit?usp=sharing"
            description = """
Тестовое задание: руководство по работе с заявками для условной системы HelpDesk.
   """

            [[params.portfolio.list]]
            title = "Центр администрирования служб DIRECTUM 5.4"
            type = "Документация"
            link = "https://club.directum.ru/webhelp/directum/5.4/index.html?ra_dac.htm"
            description = """
Раздел в руководстве администратора о сайте для настройки, запуска служб и мониторинга системы. Для доступа необходима регистрация на https://club.directum.ru.
   """

            [[params.portfolio.list]]
            title = "Архитектура системы DIRECTUM 5.4"
            type = "Документация"
            link = "https://club.directum.ru/webhelp/directum/5.4/index.html?ra_arhitektura_sistemy_directum.htm"
            description = """
Описание архитектуры системы с функциональными схемами. Для доступа необходима регистрация на https://club.directum.ru.
   """

            [[params.portfolio.list]]
            title = "Серверные события в DIRECTUM 5.4"
            type = "Документация"
            link = "https://club.directum.ru/webhelp/directum/5.4/index.html?rr_servernye_sobytiya.htm"
            description = """
Раздел в руководстве разработчика об использовании, создании и запуске серверных событий. Для доступа необходима регистрация на https://club.directum.ru.
   """

            [[params.portfolio.list]]
            title = "Функциональность веб-справки DIRECTUM 5.4"
            type = "Разработка"
            link = "https://club.directum.ru/webhelp/directum/5.4/index.html"
            description = """
Шаблон Help&Manual для сборки документации в HTML.

Функции:

- копирование ссылки на страницу;
- отправка письма в службу поддеержки;
- переход между страницами с помощью кнопок;
- полнотекстовый поиск через Zoom Search Engine. 

Для доступа необходима регистрация на https://club.directum.ru.
   """

            [[params.portfolio.list]]
            title = "Видеоплеер для веб-справки DIRECTUM 5.4"
            type = "Разработка"
            link = "https://club.directum.ru/webhelp/directum/5.4/index.html?collection_videoroliki.htm"
            description = """
Видеоплеер с плейлистом, таймкодом и кнопкой копирования ссылки. 

Для доступа необходима регистрация на https://club.directum.ru.
   """

    # Hobby section
    # [params.hobby]
    #     title = "Хобби"
    #     icon = "fas fa-futbol"
		
    #     [[params.hobby.list]]
		  #   hobby = "Футбол"
    #     [[params.hobby.list]]
		  #   hobby = "Настольные игры"
